### ISSUE TITLE
Versão do PHP

### ISSUE THREAD

**Issue by jubacchi** [luisdias/sal-plus#3]
Para qual versão do PHP o sistema foi feito?
Estou com a versão 7.4 e apresenta este erro:

Fatal error: Cannot use 'Object' as class name as it is reserved in C:\xampp\htdocs\contratos\cake\libs\object.php on line 33

**Comment by luisdias** [comment]
O sistema foi criado para a versão 5.3 do PHP.  Não pretendo atualizar para novas versões.
